# Generated by sila2.code_generator; sila2.__version__: 0.14.0
from __future__ import annotations
import time, random
from typing import TYPE_CHECKING
from sila2.server import MetadataDict
from ..generated.centrifuge import CentrifugeBase, ReadTemperature_Responses, Spin_Responses

if TYPE_CHECKING:
    from ..server import Server


class CentrifugeImpl(CentrifugeBase):
    RCF_MIN, RCF_MAX = 100.0, 5000.0
    TEMP_MIN, TEMP_MAX = 4.0, 40.0

    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)
        self._rotor_temp = 20.0

    def Spin(
        self, RCF: float, DurationSeconds: float, TemperatureCelsius: float, *, metadata: MetadataDict
    ) -> Spin_Responses:
        print(f"  [CENTRIFUGE] Spin @ {RCF:.0f}g for {DurationSeconds:.0f}s, Temp {TemperatureCelsius:.1f}°C", flush=True)
        if not (self.RCF_MIN <= RCF <= self.RCF_MAX):
            raise ValueError(f"RCF {RCF:.0f}g outside range [{self.RCF_MIN}, {self.RCF_MAX}]g")
        if TemperatureCelsius != 0.0 and not (self.TEMP_MIN <= TemperatureCelsius <= self.TEMP_MAX):
            raise ValueError(f"Temperature {TemperatureCelsius:.1f}°C outside range [{self.TEMP_MIN}, {self.TEMP_MAX}]°C")
        spin_time = 0.5 + (DurationSeconds / 3600.0) * 0.5
        time.sleep(min(2.0, spin_time))
        self._rotor_temp = TemperatureCelsius if TemperatureCelsius != 0.0 else 20.0 + random.uniform(-2, 2)
        print(f"  [CENTRIFUGE] ✓ Spin complete, rotor @ {self._rotor_temp:.1f}°C", flush=True)
        return Spin_Responses(ActualRCF=RCF, ElapsedSeconds=DurationSeconds)

    def ReadTemperature(self, *, metadata: MetadataDict) -> ReadTemperature_Responses:
        print(f"  [CENTRIFUGE] ReadTemperature", flush=True)
        self._rotor_temp += random.uniform(-0.2, 0.2)
        self._rotor_temp = round(self._rotor_temp, 1)
        print(f"  [CENTRIFUGE] ✓ Rotor temp={self._rotor_temp:.1f}°C", flush=True)
        return ReadTemperature_Responses(CurrentTemperature=self._rotor_temp)
