# Generated by sila2.code_generator; sila2.__version__: 0.14.0
from __future__ import annotations
import time, random
from typing import TYPE_CHECKING
from sila2.server import MetadataDict
from ..generated.incubator import Incubate_Responses, IncubatorBase, ReadTemperature_Responses, SetTemperature_Responses

if TYPE_CHECKING:
    from ..server import Server


class IncubatorImpl(IncubatorBase):
    TEMP_MIN, TEMP_MAX = 4.0, 95.0

    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)
        self._current_temp = 25.0
        self._target_temp = 37.0

    def SetTemperature(self, TemperatureCelsius: float, *, metadata: MetadataDict) -> SetTemperature_Responses:
        print(f"  [INCUBATOR] SetTemperature → {TemperatureCelsius:.1f}°C", flush=True)
        if not (self.TEMP_MIN <= TemperatureCelsius <= self.TEMP_MAX):
            raise ValueError(f"Temperature {TemperatureCelsius:.1f}°C outside valid range [{self.TEMP_MIN}, {self.TEMP_MAX}]°C")
        self._target_temp = TemperatureCelsius
        time.sleep(0.5)
        print(f"  [INCUBATOR] ✓ Target set to {TemperatureCelsius:.1f}°C", flush=True)
        return SetTemperature_Responses(ConfirmedTemperature=TemperatureCelsius)

    def ReadTemperature(self, *, metadata: MetadataDict) -> ReadTemperature_Responses:
        print(f"  [INCUBATOR] ReadTemperature", flush=True)
        self._current_temp += (self._target_temp - self._current_temp) * 0.1 + random.uniform(-0.05, 0.05)
        self._current_temp = round(self._current_temp, 2)
        print(f"  [INCUBATOR] ✓ Current={self._current_temp:.1f}°C, Target={self._target_temp:.1f}°C", flush=True)
        return ReadTemperature_Responses(CurrentTemperature=self._current_temp, TargetTemperature=self._target_temp)

    def Incubate(self, DurationMinutes: float, *, metadata: MetadataDict) -> Incubate_Responses:
        print(f"  [INCUBATOR] Incubate for {DurationMinutes:.1f} min", flush=True)
        sim_seconds = min(2.0, max(0.1, DurationMinutes * 0.01))
        time.sleep(sim_seconds)
        print(f"  [INCUBATOR] ✓ Incubation complete", flush=True)
        return Incubate_Responses(ElapsedTime=DurationMinutes)
