# Generated by sila2.code_generator; sila2.__version__: 0.14.0
from __future__ import annotations
import time, random
from typing import TYPE_CHECKING
from sila2.server import MetadataDict
from ..generated.phmeter import Calibrate_Responses, PHMeterBase, ReadPH_Responses

if TYPE_CHECKING:
    from ..server import Server


class PHMeterImpl(PHMeterBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)
        self._calibrated = False
        self._offset = 0.0

    def ReadPH(self, SampleId: str, *, metadata: MetadataDict) -> ReadPH_Responses:
        print(f"  [PHMETER] ReadPH {SampleId}", flush=True)
        if not self._calibrated:
            raise RuntimeError("Meter not calibrated. Call Calibrate first.")
        time.sleep(0.3)
        # Simulate realistic pH readings (mostly neutral with some variation)
        ph = round(7.0 + random.uniform(-2.0, 2.0) + self._offset, 2)
        ph = max(0.0, min(14.0, ph))  # Clamp to pH range
        temp = round(25.0 + random.uniform(-1.0, 1.0), 1)
        print(f"  [PHMETER] ✓ pH={ph:.2f} @ {temp:.1f}°C ({SampleId})", flush=True)
        return ReadPH_Responses(PHValue=ph, Temperature=temp)

    def Calibrate(self, BufferPH1: float, BufferPH2: float, *, metadata: MetadataDict) -> Calibrate_Responses:
        print(f"  [PHMETER] Calibrate with buffers pH {BufferPH1:.1f} and {BufferPH2:.1f}", flush=True)
        if not (0.0 <= BufferPH1 <= 14.0) or not (0.0 <= BufferPH2 <= 14.0):
            raise ValueError(f"Buffer pH values must be in range [0, 14]")
        if abs(BufferPH1 - BufferPH2) < 2.0:
            raise ValueError("Buffer pH values must differ by at least 2 units")
        time.sleep(0.8)
        self._calibrated = True
        self._offset = (BufferPH1 + BufferPH2) / 2.0 - 7.0
        print(f"  [PHMETER] ✓ Calibration successful", flush=True)
        return Calibrate_Responses(CalibrationStatus="Success")
