# Generated by sila2.code_generator; sila2.__version__: 0.14.0
from __future__ import annotations
import time
from typing import TYPE_CHECKING
from sila2.server import MetadataDict
from ..generated.roboticarm import MoveArm_Responses, RoboticArmBase

if TYPE_CHECKING:
    from ..server import Server


class RoboticArmImpl(RoboticArmBase):
    BOUNDS = {"X": (0.0, 300.0), "Y": (0.0, 300.0), "Z": (0.0, 250.0)}

    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)
        self._pos = (0.0, 0.0, 0.0)

    def MoveArm(self, X: float, Y: float, Z: float, *, metadata: MetadataDict) -> MoveArm_Responses:
        print(f"  [ARM]   Move → ({X:.1f}, {Y:.1f}, {Z:.1f}) mm", flush=True)
        for axis, val, (lo, hi) in [("X", X, self.BOUNDS["X"]), ("Y", Y, self.BOUNDS["Y"]), ("Z", Z, self.BOUNDS["Z"])]:
            if not (lo <= val <= hi):
                raise ValueError(f"{axis}={val:.1f} out of range [{lo}, {hi}] mm")
        dx, dy, dz = X - self._pos[0], Y - self._pos[1], Z - self._pos[2]
        dist = (dx**2 + dy**2 + dz**2) ** 0.5
        time.sleep(min(2.0, dist / 200.0 + 0.2))
        self._pos = (X, Y, Z)
        print(f"  [ARM]   ✓ Reached ({X:.1f}, {Y:.1f}, {Z:.1f})", flush=True)
        return MoveArm_Responses(ReachedX=X, ReachedY=Y, ReachedZ=Z)
