# Generated by sila2.code_generator; sila2.__version__: 0.14.0
from __future__ import annotations
import random, time
from typing import TYPE_CHECKING
from sila2.server import MetadataDict
from ..generated.spectrophotometer import ReadAbsorbance_Responses, SpectrophotometerBase

if TYPE_CHECKING:
    from ..server import Server


class SpectrophotometerImpl(SpectrophotometerBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)

    def ReadAbsorbance(self, VesselId: str, WavelengthNm: float, *, metadata: MetadataDict) -> ReadAbsorbance_Responses:
        print(f"  [SPECTRO] ReadAbsorbance {VesselId} @ {WavelengthNm:.0f} nm", flush=True)
        if not (200.0 <= WavelengthNm <= 1000.0):
            raise ValueError(f"Wavelength {WavelengthNm:.0f} nm out of range [200, 1000]")
        time.sleep(0.8)
        absorbance = round(random.uniform(0.05, 1.8), 4)
        print(f"  [SPECTRO] ✓ A={absorbance:.4f} AU @ {WavelengthNm:.0f} nm ({VesselId})", flush=True)
        return ReadAbsorbance_Responses(Absorbance=absorbance, WavelengthNm=WavelengthNm)
