# Generated by sila2.code_generator; sila2.__version__: 0.14.0
from __future__ import annotations
import math, random, time
from typing import TYPE_CHECKING
from sila2.server import MetadataDict
from ..generated.spectrophotometer import ReadAbsorbance_Responses, SpectrophotometerBase

if TYPE_CHECKING:
    from ..server import Server

# Gaussian wavelength transfer function centred on visible absorption peak
_PEAK_NM = 500.0
_SIGMA_NM = 150.0
_BASELINE_AU = 0.001  # instrument dark-current baseline


class SpectrophotometerImpl(SpectrophotometerBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)
        self._registry = parent_server.vessel_registry

    def ReadAbsorbance(self, VesselId: str, WavelengthNm: float, *, metadata: MetadataDict) -> ReadAbsorbance_Responses:
        print(f"  [SPECTRO] ReadAbsorbance {VesselId} @ {WavelengthNm:.0f} nm", flush=True)
        if not (200.0 <= WavelengthNm <= 1000.0):
            raise ValueError(f"Wavelength {WavelengthNm:.0f} nm out of range [200, 1000]")
        time.sleep(0.8)

        vessel = self._registry.get_vessel(VesselId)
        fill = self._registry.get_fill_fraction(VesselId)

        # Beer-Lambert: A = ε × c × l, using fill fraction as concentration proxy
        A_base = vessel.absorbance_coefficient * fill * vessel.path_length_cm
        wl_factor = math.exp(-0.5 * ((WavelengthNm - _PEAK_NM) / _SIGMA_NM) ** 2)
        A_det = A_base * wl_factor
        absorbance = max(_BASELINE_AU, round(A_det * random.uniform(0.98, 1.02), 4))

        print(f"  [SPECTRO] ✓ A={absorbance:.4f} AU @ {WavelengthNm:.0f} nm ({VesselId}, fill={fill:.1%})", flush=True)
        return ReadAbsorbance_Responses(Absorbance=absorbance, WavelengthNm=WavelengthNm)
