# Generated by sila2.code_generator; sila2.__version__: 0.14.0

from typing import Optional
from uuid import UUID, uuid4

from sila2.server import SilaServer

from .vessel_state import VesselRegistry
from .feature_implementations.centrifuge_impl import CentrifugeImpl
from .feature_implementations.incubator_impl import IncubatorImpl
from .feature_implementations.liquidhandler_impl import LiquidHandlerImpl
from .feature_implementations.phmeter_impl import PHMeterImpl
from .feature_implementations.roboticarm_impl import RoboticArmImpl
from .feature_implementations.spectrophotometer_impl import SpectrophotometerImpl
from .generated.centrifuge import CentrifugeFeature
from .generated.incubator import IncubatorFeature
from .generated.liquidhandler import LiquidHandlerFeature
from .generated.phmeter import PHMeterFeature
from .generated.roboticarm import RoboticArmFeature
from .generated.spectrophotometer import SpectrophotometerFeature


class Server(SilaServer):
    vessel_registry: VesselRegistry

    def __init__(
        self,
        server_uuid: Optional[UUID] = None,
        name: Optional[str] = None,
        description: Optional[str] = None,
    ):
        if name is None:
            name = "AxiomLab Mock"
        if description is None:
            description = "Mock SiLA 2 server with 6 instruments: LiquidHandler, RoboticArm, Spectrophotometer, Incubator, Centrifuge, PHMeter"
        super().__init__(
            server_name=name,
            server_description=description,
            server_type="AxiomlabMock",
            server_version="0.1",
            server_vendor_url="https://axiomlab.local",
            server_uuid=server_uuid if server_uuid is not None else uuid4(),
        )

        self.vessel_registry = VesselRegistry()

        self.centrifuge = CentrifugeImpl(self)
        self.set_feature_implementation(CentrifugeFeature, self.centrifuge)

        self.incubator = IncubatorImpl(self)
        self.set_feature_implementation(IncubatorFeature, self.incubator)

        self.liquidhandler = LiquidHandlerImpl(self)
        self.set_feature_implementation(LiquidHandlerFeature, self.liquidhandler)

        self.phmeter = PHMeterImpl(self)
        self.set_feature_implementation(PHMeterFeature, self.phmeter)

        self.roboticarm = RoboticArmImpl(self)
        self.set_feature_implementation(RoboticArmFeature, self.roboticarm)

        self.spectrophotometer = SpectrophotometerImpl(self)
        self.set_feature_implementation(SpectrophotometerFeature, self.spectrophotometer)
