# Generated by sila2.code_generator; sila2.__version__: 0.14.0
from __future__ import annotations
import random, time
from typing import TYPE_CHECKING
from sila2.server import MetadataDict
from ..generated.liquidhandler import Aspirate_Responses, Dispense_Responses, LiquidHandlerBase

if TYPE_CHECKING:
    from ..server import Server


class LiquidHandlerImpl(LiquidHandlerBase):
    MAX_VOL, MIN_VOL = 1000.0, 0.5

    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)
        self._registry = parent_server.vessel_registry

    def Dispense(self, TargetVessel: str, VolumeUl: float, *, metadata: MetadataDict) -> Dispense_Responses:
        print(f"  [PUMP]  Dispense → {TargetVessel}  {VolumeUl:.1f} µL", flush=True)
        if VolumeUl > self.MAX_VOL:
            raise ValueError(f"Volume {VolumeUl:.1f} µL exceeds hardware cap of {self.MAX_VOL} µL")
        if VolumeUl < self.MIN_VOL:
            raise ValueError(f"Volume {VolumeUl:.1f} µL below minimum {self.MIN_VOL} µL")
        actual = round(VolumeUl * random.uniform(0.99, 1.01), 2)
        self._registry.dispense(TargetVessel, actual)
        time.sleep(0.3 + (VolumeUl / self.MAX_VOL) * 0.5)
        new_vol = self._registry.get_volume(TargetVessel)
        print(f"  [PUMP]  ✓ Dispensed {actual:.2f} µL into {TargetVessel} (now {new_vol:.1f} µL)", flush=True)
        return Dispense_Responses(DispensedVolumeUl=actual)

    def Aspirate(self, SourceVessel: str, VolumeUl: float, *, metadata: MetadataDict) -> Aspirate_Responses:
        print(f"  [PUMP]  Aspirate ← {SourceVessel}  {VolumeUl:.1f} µL", flush=True)
        if VolumeUl > self.MAX_VOL:
            raise ValueError(f"Volume {VolumeUl:.1f} µL exceeds hardware cap of {self.MAX_VOL} µL")
        actual = round(VolumeUl * random.uniform(0.99, 1.01), 2)
        self._registry.aspirate(SourceVessel, actual)
        time.sleep(0.3 + (VolumeUl / self.MAX_VOL) * 0.4)
        new_vol = self._registry.get_volume(SourceVessel)
        print(f"  [PUMP]  ✓ Aspirated {actual:.2f} µL from {SourceVessel} (now {new_vol:.1f} µL)", flush=True)
        return Aspirate_Responses(AspiratedVolumeUl=actual)
