use proof_artifacts::manifest::{
    ActionPolicy, ArtifactStatus, BuildIdentity, ProofArtifact, ProofManifest, RiskClass,
    VerusArtifact,
};
use proof_artifacts::policy::{ExecutionContext, RuntimePolicyEngine};
use std::collections::BTreeMap;

/// Build the runtime proof manifest and policy engine that gate high-risk hardware actions.
///
/// Loads `proof_artifacts/vessel_physics_manifest.json` — the real Verus compiler
/// output generated by `python3 vessel_physics/generate_manifest.py`.
/// If the file is not found, artifacts are marked Failed and high-risk actions
/// will be denied until the manifest is regenerated.
pub(crate) fn build_policy_engine() -> (RuntimePolicyEngine, ExecutionContext) {
    let (manifest, ctx) = build_proof_manifest();
    let engine = RuntimePolicyEngine::new(manifest).mark_signature_verified();
    (engine, ctx)
}

fn build_proof_manifest() -> (ProofManifest, ExecutionContext) {
    let git_commit  = std::env::var("AXIOMLAB_GIT_COMMIT").unwrap_or_else(|_| "dev".into());
    let binary_hash = compute_binary_hash();
    let artifacts   = load_manifest_artifacts();

    let manifest = ProofManifest {
        schema_version: 1,
        generated_unix_secs: std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs(),
        build: BuildIdentity {
            git_commit: git_commit.clone(),
            binary_hash: binary_hash.clone(),
            workspace_hash: "workspace".into(),
            container_image_digest: None,
            device_id: None,
            firmware_version: None,
        },
        artifacts,
        actions: vec![
            ActionPolicy {
                action: "move_arm".into(),
                risk_class: RiskClass::Actuation,
                required_artifacts: vec!["lab_safety_verus".into()],
                rationale: "Arm actuation requires Verus-proven safety bounds".into(),
            },
            ActionPolicy {
                action: "dispense".into(),
                risk_class: RiskClass::LiquidHandling,
                required_artifacts: vec!["lab_safety_verus".into()],
                rationale: "Liquid handling requires verified volume constraints".into(),
            },
            ActionPolicy {
                action: "aspirate".into(),
                risk_class: RiskClass::LiquidHandling,
                required_artifacts: vec!["lab_safety_verus".into()],
                rationale: "Aspirate requires verified volume constraints".into(),
            },
            ActionPolicy {
                action: "set_temperature".into(),
                risk_class: RiskClass::Actuation,
                required_artifacts: vec!["lab_safety_verus".into()],
                rationale: "Temperature control requires verified thermal bounds".into(),
            },
            ActionPolicy {
                action: "spin_centrifuge".into(),
                risk_class: RiskClass::Actuation,
                required_artifacts: vec!["lab_safety_verus".into()],
                rationale: "Centrifuge requires verified RCF bounds".into(),
            },
            ActionPolicy {
                action: "read_absorbance".into(),
                risk_class: RiskClass::ReadOnly,
                required_artifacts: vec![],
                rationale: "Read-only measurement, no proof required".into(),
            },
            ActionPolicy {
                action: "read_temperature".into(),
                risk_class: RiskClass::ReadOnly,
                required_artifacts: vec![],
                rationale: "Read-only measurement, no proof required".into(),
            },
            ActionPolicy {
                action: "read_ph".into(),
                risk_class: RiskClass::ReadOnly,
                required_artifacts: vec![],
                rationale: "Read-only measurement, no proof required".into(),
            },
            ActionPolicy {
                action: "read_sensor".into(),
                risk_class: RiskClass::ReadOnly,
                required_artifacts: vec![],
                rationale: "Read-only sensor, no proof required".into(),
            },
            ActionPolicy {
                action: "calibrate_ph".into(),
                risk_class: RiskClass::ReadOnly,
                required_artifacts: vec![],
                rationale: "Calibration is non-destructive".into(),
            },
            ActionPolicy {
                action: "incubate".into(),
                risk_class: RiskClass::Actuation,
                required_artifacts: vec!["lab_safety_verus".into()],
                rationale: "Incubation requires verified thermal bounds".into(),
            },
        ],
    };

    let ctx = ExecutionContext {
        git_commit,
        binary_hash,
        container_image_digest: None,
        device_id: None,
        firmware_version: None,
    };

    (manifest, ctx)
}

fn compute_binary_hash() -> String {
    use sha2::{Digest, Sha256};
    match std::env::current_exe().and_then(|p| std::fs::read(p)) {
        Ok(bytes) => hex::encode(Sha256::digest(&bytes)),
        Err(_) => "unknown".into(),
    }
}

/// Try to load artifact records from the committed Verus manifest file.
///
/// Searches for `proof_artifacts/vessel_physics_manifest.json` relative to the
/// working directory or one level up (covers both `cargo run` from workspace
/// root and from `server/`). Falls back to Failed-status artifacts so that
/// high-risk actions are denied until the manifest is regenerated.
fn load_manifest_artifacts() -> Vec<ProofArtifact> {
    let candidates = [
        "proof_artifacts/vessel_physics_manifest.json",
        "../proof_artifacts/vessel_physics_manifest.json",
    ];
    for path in &candidates {
        if let Ok(raw) = std::fs::read_to_string(path) {
            match serde_json::from_str::<ProofManifest>(&raw) {
                Ok(m) => {
                    tracing::info!(
                        path = path,
                        artifact_count = m.artifacts.len(),
                        "Loaded Verus proof manifest"
                    );
                    return m.artifacts;
                }
                Err(e) => {
                    tracing::warn!("Failed to parse manifest at {path}: {e}");
                }
            }
        }
    }
    tracing::warn!(
        "Proof manifest not found — high-risk actions will be denied. \
         Regenerate with: python3 vessel_physics/generate_manifest.py"
    );
    vec![ProofArtifact {
        id: "lab_safety_verus".into(),
        source_path: "verus_verified/vessel_registry.rs".into(),
        source_hash: "unknown".into(),
        mir_path: None,
        mir_hash: None,
        lean: vec![],
        verus: Some(VerusArtifact {
            path: "verus_verified/vessel_registry.rs".into(),
            hash: "unknown".into(),
            status: ArtifactStatus::Failed,
        }),
        theorem_count: 0,
        sorry_count: 0,
        status: ArtifactStatus::Failed,
        metadata: BTreeMap::new(),
    }]
}
