# Generated by sila2.code_generator; sila2.__version__: 0.14.0
# Lazy imports via PEP 562 so that sila2-independent submodules (e.g.
# vessel_state) can be imported without requiring sila2 to be installed.
# Runtime behaviour when sila2 IS installed is identical.
from __future__ import annotations

__all__ = ["Client", "Server"]


def __getattr__(name: str):
    if name == "Client":
        from .generated import Client
        return Client
    if name == "Server":
        from .server import Server
        return Server
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
