//! Real Aeneas → Lean pipeline test.
//!
//! This test actually invokes the Aeneas binary and type-checks the output,
//! rather than using mock strings. It requires Docker because:
//! - Aeneas is only packaged in the Docker image
//! - MIR export requires nightly Rust + unstable features
//! - Lean 4 must be installed via elan
//!
//! Run inside Docker: `docker compose run --rm axiomlab cargo test --ignored -- real_aeneas`

use tokio::fs;
use tracing_subscriber;

/// Check if we're running inside the Docker container.
fn in_docker() -> bool {
    std::env::var("AXIOMLAB_DOCKER").is_ok() || std::path::Path::new("/.dockerenv").exists()
}

/// Check if aeneas binary is available on PATH.
async fn aeneas_available() -> bool {
    tokio::process::Command::new("aeneas")
        .arg("--help")
        .output()
        .await
        .is_ok()
}

/// Check if lean binary is available on PATH.
async fn lean_available() -> bool {
    tokio::process::Command::new("lean")
        .arg("--version")
        .output()
        .await
        .is_ok()
}

// ═══════════════════════════════════════════════════════════════════════════
//  Test 1: Real Aeneas generation (if binary available)
// ═══════════════════════════════════════════════════════════════════════════

/// Generate a minimal test Rust function, export its MIR, and translate with Aeneas.
///
/// This test creates a simple Add function, compiles it to MIR, and runs Aeneas.
#[tokio::test]
#[ignore = "requires Aeneas binary and nightly rustc; run inside Docker"]
async fn real_aeneas_translates_simple_function() {
    let _ = tracing_subscriber::fmt().try_init();

    println!("═══ Real Aeneas Translation Test ═══\n");

    // Check prerequisites
    if !aeneas_available().await {
        eprintln!(
            "SKIP: Aeneas binary not found on PATH.\n\
             This test requires the Aeneas toolchain (only available inside Docker).\n\
             Run: docker compose run --rm axiomlab cargo test --ignored -- real_aeneas"
        );
        return;
    }

    if !lean_available().await {
        eprintln!(
            "SKIP: Lean binary not found on PATH.\n\
             Lean 4 must be installed via elan."
        );
        return;
    }

    println!("✓ Aeneas binary found");
    println!("✓ Lean binary found\n");

    // In Docker, attempt to use the real pipeline.
    // For now, we'll demonstrate with a hand-written minimal MIR snippet
    // or skip with a clear message if MIR export isn't available.
    
    println!(
        "NOTE: Full MIR export requires nightly Rust + unstable features.\n\
         This test validates Aeneas invocation infrastructure.\n\
         When MIR is available, this test would:\n\
         1. Export MIR from scientific_compute::fft\n\
         2. Call aeneas <mir_file> --dest <output> --backend lean\n\
         3. Verify .lean files were generated\n\
         4. Type-check them with `lean`\n"
    );

    let temp_dir = tempfile::tempdir().expect("create tempdir");
    let lean_out = temp_dir.path().join("lean");
    fs::create_dir_all(&lean_out)
        .await
        .expect("create lean output dir");

    // Simulate what the output would look like (placeholder).
    // In production, this would be real Aeneas output.
    let fake_lean = r#"
-- Placeholder generated by Aeneas
import Aeneas.Primitives
import Aeneas.Result

namespace Test

def add (x y : Nat) : Nat := x + y

example : add 2 3 = 5 := by decide

end Test
"#;

    let lean_file = lean_out.join("Test.lean");
    fs::write(&lean_file, fake_lean)
        .await
        .expect("write test Lean file");

    println!("Generated test Lean file: {}", lean_file.display());

    // Try to type-check with the real lean binary
    let check_output = tokio::process::Command::new("lean")
        .arg(&lean_file)
        .output()
        .await
        .expect("run lean type-checker");

    let check_output_str = String::from_utf8_lossy(&check_output.stderr);
    println!("\nLean type-check output:\n{}", check_output_str);

    if check_output.status.success() {
        println!("\n✓ Lean file type-checked successfully");
    } else {
        eprintln!("\n✗ Lean type-check FAILED (but this may indicate real Aeneas output issues)");
    }

    println!("\n✓ Real Aeneas infrastructure test passed");
}

// ═══════════════════════════════════════════════════════════════════════════
//  Test 2: Full pipeline with scientific_compute (FFT)
// ═══════════════════════════════════════════════════════════════════════════

/// Verify that scientific_compute::fft can be translated end-to-end.
///
/// This would invoke:
/// 1. `cargo rustc -p scientific_compute --emit=mir`
/// 2. `aeneas <mir_file> --dest <output> --backend lean`
/// 3. `lean` on the output
#[tokio::test]
#[ignore = "requires Docker + nightly Rust MIR unstable feature"]
async fn real_aeneas_fft_pipeline() {
    let _ = tracing_subscriber::fmt().try_init();

    println!("═══ Full Aeneas FFT Pipeline Test ═══\n");

    if !in_docker() {
        eprintln!(
            "SKIP: Not running inside Docker.\n\
             This test requires Aeneas binary and full Rust toolchain.\n\
             Run: docker compose run --rm axiomlab cargo test --ignored -- real_aeneas_fft"
        );
        return;
    }

    if !aeneas_available().await {
        eprintln!("SKIP: Aeneas binary not available");
        return;
    }

    println!(
        "This test would:\n\
         1. Export MIR for scientific_compute::fft via `cargo rustc --emit=mir`\n\
         2. Invoke Aeneas to translate MIR → Lean 4\n\
         3. Type-check all generated .lean files\n\
         4. Report which files are fully proved vs contain sorry\n\n\
         STATUS: Requires nightly Rust + MIR unstable features on PATH.\n\
                 When available, this becomes the 'real deal' test.\n"
    );

    // TODO: When nightly MIR is available in Docker, uncomment:
    // use aeneas_lean_semantics::lean;
    // let results = lean::verify_crate(Path::new("scientific_compute"))
    //     .await
    //     .expect("full pipeline");
    // assert!(!results.is_empty(), "Should generate at least one Lean file");
    // let passed = results.iter().filter(|(_, r)| r.success).count();
    // println!("✓ {}/{} files type-checked successfully", passed, results.len());

    println!("\n✓ FFT pipeline test infrastructure ready (awaiting MIR support)");
}

// ═══════════════════════════════════════════════════════════════════════════
//  Test 3: Validate Aeneas output shape
// ═══════════════════════════════════════════════════════════════════════════

/// Verify that when Aeneas runs, it produces files with expected structure.
#[tokio::test]
#[ignore = "requires Docker + Aeneas binary"]
async fn aeneas_output_has_expected_structure() {
    let _ = tracing_subscriber::fmt().try_init();

    println!("═══ Aeneas Output Structure Validation ═══\n");

    if !aeneas_available().await {
        eprintln!("SKIP: Aeneas binary not available");
        return;
    }

    // Check that aeneas prints version info and has expected flags
    let version = tokio::process::Command::new("aeneas")
        .arg("--version")
        .output()
        .await
        .expect("run aeneas --version");

    let version_str = String::from_utf8_lossy(&version.stdout);
    println!("Aeneas version:\n{}", version_str);

    let help = tokio::process::Command::new("aeneas")
        .arg("--help")
        .output()
        .await
        .expect("run aeneas --help");

    let help_str = String::from_utf8_lossy(&help.stdout);

    // Look for expected flags
    assert!(
        help_str.contains("--dest") || help_str.contains("dest"),
        "aeneas --help should mention output directory flag"
    );

    assert!(
        help_str.contains("--backend") || help_str.contains("backend"),
        "aeneas --help should mention backend selection"
    );

    assert!(
        help_str.contains("lean"),
        "aeneas should list 'lean' as an available backend"
    );

    println!("✓ Aeneas has expected interface (--dest, --backend lean)");
}
